- hosts: all
  tasks:
    - name: Send a text message to a mobile phone through Twilio
      community.general.twilio:
        msg: "All servers with webserver role are now configured."
        account_sid: "ACbd68daece4606345b8730a3bb0e0c721"
        auth_token: "8a636bbf73d084a883e55347718c2aa3"
        from_number: "+17192590683"
        to_number: "+919510407509"


    - name: Sending an e-mail using Gmail SMTP servers
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: studytime12science@gmail.com
        password: xbqw mzld zylx gdvq
        to: matlab1694@gmail.com
        subject: Ansible-report
        body: System {{ ansible_hostname }} has been successfully provisioned.

